name: 'Test variables'
on:
  workflow_dispatch:
env:
  NEW_ENV: ${{ vars.ELOSZKI_VAR }}

jobs:
  Check-variable-from-env:
    name: Check variabls from env
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - run: echo "ENVIR $NEW_ENV"

  no-env-check:
    name: Check variabls from repo
    runs-on: ubuntu-latest
    steps:
      - run: echo "REPO $NEW_ENV"
    
