name: Test of gh api and gh cli
on: 
  workflow_disptach:

job:
  test:
    name: test
    run_on: ubuntu-latest

    steps:
      - name: gh api
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/devnickxyz/cloud-iac-training/environments

      - name: gh cli
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/devnickxyz/cloud-iac-training/environments
          
    
